"""
hybrid_recommender.py
─────────────────────
Hybrid recommendation pipeline that combines:
  1. Rule-based clinical mapping        (rule_engine)
  2. Risk-weighted scoring + ranking    (risk_weighting)
  3. LLM-based natural language layer   (llm_personalizer)

Exposes a single public function: generate_recommendations()
"""

import sys, os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from typing import Dict, Any, List, Optional

from phase3_recommendation_engine.rule_engine import apply_clinical_rules
from phase3_recommendation_engine.risk_weighting import (
    compute_weighted_scores,
    normalize_and_rank,
    apply_age_personalization,
    apply_severity_boost,
)
from phase3_recommendation_engine.clinical_thresholds import (
    classify_risk_band,
    classify_age_group,
    FEATURE_ALIAS_MAP,
)
from phase3_recommendation_engine.llm_personalizer import personalize_with_llm

# Standard disclaimer (appears in every output)
DISCLAIMER = (
    "This report is generated by an AI system for educational and informational purposes only. "
    "It does not constitute medical advice, diagnosis, or treatment. "
    "All lifestyle changes should be discussed with a qualified healthcare professional before implementation."
)

# General wellness advice issued regardless of specific risk triggers
GENERAL_WELLNESS_ADVICE = [
    "Maintain a regular sleep schedule of 7–9 hours per night to support hormonal regulation and metabolic health.",
    "Stay adequately hydrated (≥2.0 L/day of water) and limit sugar-sweetened beverages.",
    "Schedule annual comprehensive health screening including lipid panel, HbA1c, and blood pressure measurement.",
    "Limit ultra-processed food consumption; prioritize whole foods, legumes, and colorful vegetables.",
    "Practice evidence-based stress reduction techniques (mindfulness meditation, diaphragmatic breathing) to lower cortisol.",
]


def _normalize_profile(patient_profile: Dict[str, Any]) -> Dict[str, float]:
    """Canonicalize profile keys using the alias map."""
    normalized = {}
    for k, v in patient_profile.items():
        canonical = FEATURE_ALIAS_MAP.get(k.lower(), k)
        normalized[canonical] = float(v)
    return normalized


def _build_shap_map(
    top_positive_risk_factors: List[str],
    protective_factors: List[str],
) -> Dict[str, float]:
    """
    Parse the string-formatted SHAP factor lists from Phase 2 output
    into a {FeatureName: shap_value} dict.

    Expected format: "FeatureName (value)"  e.g. "Glucose (1.23)"
    """
    shap_map: Dict[str, float] = {}

    def _parse_list(items: List[str], sign: float):
        for item in items:
            # Extract feature name before the first '('
            if "(" in item:
                parts = item.split("(")
                feature = parts[0].strip()
                try:
                    value = float(parts[1].replace(")", "").strip())
                except ValueError:
                    value = 0.5
            else:
                feature = item.strip()
                value = 0.5
            canonical = FEATURE_ALIAS_MAP.get(feature.lower(), feature)
            shap_map[canonical] = sign * abs(value)

    _parse_list(top_positive_risk_factors, +1.0)
    _parse_list(protective_factors, -1.0)
    return shap_map


def generate_recommendations(
    predicted_risks: Dict[str, float],
    top_positive_risk_factors: List[str],
    protective_factors: List[str],
    patient_profile: Dict[str, Any],
    use_llm: bool = True,
    llm_api_key: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Full hybrid recommendation pipeline.

    Parameters
    ----------
    predicted_risks             : {'diabetes': 0.72, 'heart_disease': 0.55}
    top_positive_risk_factors   : From Phase 2 local explainability
    protective_factors          : From Phase 2 local explainability
    patient_profile             : Raw biomarker dict (any key casing)
    use_llm                     : If True, enhance with LLM language layer
    llm_api_key                 : Optional API key for LLM service

    Returns
    -------
    Structured output dict matching the RW-AWRM specification.
    """
    # 1. Normalize patient profile keys
    profile = _normalize_profile(patient_profile)

    # 2. Build SHAP contribution map from Phase 2 string outputs
    shap_map = _build_shap_map(top_positive_risk_factors, protective_factors)

    # 3. Classify patient context
    age = int(profile.get("Age", 45))
    age_group  = classify_age_group(age)

    # 4. Apply rule engine
    raw_recs = apply_clinical_rules(profile)

    # 5. Score each recommendation
    scored_recs = compute_weighted_scores(raw_recs, predicted_risks, shap_map)

    # 6. Normalize + rank
    ranked_recs = normalize_and_rank(scored_recs)

    # 7. Personalization layers
    ranked_recs = apply_age_personalization(ranked_recs, age_group)
    ranked_recs = apply_severity_boost(ranked_recs, predicted_risks)

    # 8. Optional: LLM enhancement layer
    if use_llm:
        ranked_recs = personalize_with_llm(
            recommendations=ranked_recs,
            patient_profile=profile,
            predicted_risks=predicted_risks,
            age_group=age_group,
            api_key=llm_api_key,
        )

    # 9. Format final output
    prioritized = []
    for rec in ranked_recs:
        prioritized.append({
            "recommendation": rec.get("llm_recommendation", rec["recommendation"]),
            "priority_score": rec["priority_score"],
            "related_risk":   rec["related_risk"],
            "justification":  rec.get("llm_justification", rec["justification"]),
        })

    return {
        "patient_context": {
            "age_group":   age_group,
            "risk_levels": {k: classify_risk_band(v) for k, v in predicted_risks.items()},
        },
        "prioritized_recommendations": prioritized,
        "general_wellness_advice": GENERAL_WELLNESS_ADVICE,
        "disclaimer": DISCLAIMER,
    }


def generate_rule_only_recommendations(
    predicted_risks: Dict[str, float],
    top_positive_risk_factors: List[str],
    protective_factors: List[str],
    patient_profile: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Rule-only version of the pipeline (no LLM). Used for comparison in evaluation.
    """
    return generate_recommendations(
        predicted_risks=predicted_risks,
        top_positive_risk_factors=top_positive_risk_factors,
        protective_factors=protective_factors,
        patient_profile=patient_profile,
        use_llm=False,
        llm_api_key=None,
    )
